file_write = input('Enter text to write to the file:')
file1 = open('output.txt','w')
file1.write(file_write)
print('Data successfully writen to {}.'.format(file1.name))
file1.close()
file_append = input('Enter additional text to append:')
file1 = open('output.txt','a')
file1.write('\n')
file1.write(file_append)
print('Data successfully appended')
file1.close()
file1 = open('output.txt','r')
print('Final contents of {}:'.format(file1.name))
print(file1.read())
file1.close()
